final List<Map<String, String>> creators = [
  {
    'name': 'Altafur Rahman Fuad',
    'role': 'Developer A',
    'image': 'assets/images/fuad.jpg',
    'mobile': '8801712345678',
    'university': 'ABC University',
    'facebook': 'fb.com/fuad.profile',
    'linkedin': 'linkedin.com/in/fuaddev',
    'instagram': 'instagram.com/fuad.ig',
    'email': 'fuad@example.com',
    'skills': 'Flutter, Firebase, UI/UX',
    'expertise': 'Mobile App Development, Database Design',
  },
  {
    'name': 'Chandni Barua',
    'role': 'Designer B',
    'image': 'assets/images/chadni.jpg',
    'mobile': '8801712345679',
    'university': 'XYZ University',
    'facebook': 'fb.com/chandni.profile',
    'linkedin': 'linkedin.com/in/chandnidesign',
    'instagram': 'instagram.com/chandni.ig',
    'email': 'chandni@example.com',
    'skills': 'Adobe XD, Figma, Graphic Design',
    'expertise': 'UI/UX Design, Branding',
  },
  {
    'name': 'Nibrita Barua',
    'role': 'Tester C',
    'image': 'assets/images/nibrita.jpg',
    'mobile': '8801712345680',
    'university': 'DEF University',
    'facebook': 'fb.com/nibrita.profile',
    'linkedin': 'linkedin.com/in/nibritatest',
    'instagram': 'instagram.com/nibrita.ig',
    'email': 'nibrita@example.com',
    'skills': 'Manual Testing, Automation Testing',
    'expertise': 'QA Testing, Bug Tracking',
  },
  {
    'name': 'Maysha Ayman Ana',
    'role': 'Manager D',
    'image': 'assets/images/maysha.jpg',
    'mobile': '8801712345681',
    'university': 'GHI University',
    'facebook': 'fb.com/maysha.profile',
    'linkedin': 'linkedin.com/in/mayshamanage',
    'instagram': 'instagram.com/maysha.ig',
    'email': 'maysha@example.com',
    'skills': 'Project Management, Agile',
    'expertise': 'Team Leadership, Product Management',
  },
  {
    'name': 'Riazul Kabir Pavel',
    'role': 'Developer E',
    'image': 'assets/images/pavel.jpg',
    'mobile': '8801712345682',
    'university': 'JKL University',
    'facebook': 'fb.com/pavel.profile',
    'linkedin': 'linkedin.com/in/paveldev',
    'instagram': 'instagram.com/pavel.ig',
    'email': 'pavel@example.com',
    'skills': 'Backend Development, APIs',
    'expertise': 'Server-side Programming, Database',
  },
];
